// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolChainEnabler) DeepCopyInto(out *ToolChainEnabler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolChainEnabler.
func (in *ToolChainEnabler) DeepCopy() *ToolChainEnabler {
	if in == nil {
		return nil
	}
	out := new(ToolChainEnabler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolChainEnabler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolChainEnablerList) DeepCopyInto(out *ToolChainEnablerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ToolChainEnabler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolChainEnablerList.
func (in *ToolChainEnablerList) DeepCopy() *ToolChainEnablerList {
	if in == nil {
		return nil
	}
	out := new(ToolChainEnablerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolChainEnablerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolChainEnablerSpec) DeepCopyInto(out *ToolChainEnablerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolChainEnablerSpec.
func (in *ToolChainEnablerSpec) DeepCopy() *ToolChainEnablerSpec {
	if in == nil {
		return nil
	}
	out := new(ToolChainEnablerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolChainEnablerStatus) DeepCopyInto(out *ToolChainEnablerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolChainEnablerStatus.
func (in *ToolChainEnablerStatus) DeepCopy() *ToolChainEnablerStatus {
	if in == nil {
		return nil
	}
	out := new(ToolChainEnablerStatus)
	in.DeepCopyInto(out)
	return out
}
